.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract-gas 1  StarForge "User Manual"
.SH NAME
starforge\-contract\-gas \- Gas analysis and optimization helpers
.SH SYNOPSIS
\fBstarforge\-contract\-gas\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Gas analysis and optimization helpers
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
