.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-deploy-orchestrate 1  StarForge "User Manual"
.SH NAME
starforge\-deploy\-orchestrate \- Multi\-contract deployment orchestration
.SH SYNOPSIS
\fBstarforge\-deploy\-orchestrate\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Multi\-contract deployment orchestration
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
