.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-deploy-backup 1  StarForge "User Manual"
.SH NAME
starforge\-deploy\-backup \- Backup and disaster recovery for contract state
.SH SYNOPSIS
\fBstarforge\-deploy\-backup\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Backup and disaster recovery for contract state
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
