.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-network-node 1  StarForge "User Manual"
.SH NAME
starforge\-network\-node \- Local Soroban devnet (Docker quickstart)
.SH SYNOPSIS
\fBstarforge\-network\-node\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Local Soroban devnet (Docker quickstart)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
