.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-project-collab 1  StarForge "User Manual"
.SH NAME
starforge\-project\-collab \- AI\-driven collaboration tools
.SH SYNOPSIS
\fBstarforge\-project\-collab\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
AI\-driven collaboration tools
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
