.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract-profile 1  StarForge "User Manual"
.SH NAME
starforge\-contract\-profile \- Advanced contract performance analysis and profiling
.SH SYNOPSIS
\fBstarforge\-contract\-profile\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Advanced contract performance analysis and profiling
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
