.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-network-snapshot 1  StarForge "User Manual"
.SH NAME
starforge\-network\-snapshot \- Deterministic live\-ledger snapshots for local tests
.SH SYNOPSIS
\fBstarforge\-network\-snapshot\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Deterministic live\-ledger snapshots for local tests
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
