.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-template-registry 1  StarForge "User Manual"
.SH NAME
starforge\-template\-registry \- Interact with the remote template registry
.SH SYNOPSIS
\fBstarforge\-template\-registry\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Interact with the remote template registry
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
