.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-wallet-diagnostics 1  StarForge "User Manual"
.SH NAME
starforge\-wallet\-diagnostics \- Connectivity diagnostics for Ledger/Trezor devices
.SH SYNOPSIS
\fBstarforge\-wallet\-diagnostics\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Connectivity diagnostics for Ledger/Trezor devices
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
