.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract-test 1  StarForge "User Manual"
.SH NAME
starforge\-contract\-test \- Contract testing utilities for Soroban wasm
.SH SYNOPSIS
\fBstarforge\-contract\-test\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Contract testing utilities for Soroban wasm
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
