.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-wallet-multisig 1  StarForge "User Manual"
.SH NAME
starforge\-wallet\-multisig \- Manage multi\-signature transactions
.SH SYNOPSIS
\fBstarforge\-wallet\-multisig\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Manage multi\-signature transactions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
