.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-template 1  StarForge "User Manual"
.SH NAME
starforge\-template \- Manage community contract templates
.SH SYNOPSIS
\fBstarforge\-template\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Manage community contract templates
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
