.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-ai-suggest 1  StarForge "User Manual"
.SH NAME
starforge\-ai\-suggest \- AI contract function suggestions
.SH SYNOPSIS
\fBstarforge\-ai\-suggest\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
AI contract function suggestions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
