.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-wallet-tx 1  StarForge "User Manual"
.SH NAME
starforge\-wallet\-tx \- Fetch a transaction for the account
.SH SYNOPSIS
\fBstarforge\-wallet\-tx\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Fetch a transaction for the account
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
