.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract-storage 1  StarForge "User Manual"
.SH NAME
starforge\-contract\-storage \- Deep contract storage inspection (state, key, storage)
.SH SYNOPSIS
\fBstarforge\-contract\-storage\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Deep contract storage inspection (state, key, storage)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
