.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-completions 1  StarForge "User Manual"
.SH NAME
starforge\-completions \- Generate shell completions for bash, zsh, fish, powershell
.SH SYNOPSIS
\fBstarforge\-completions\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Generate shell completions for bash, zsh, fish, powershell
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
