.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-tool-tutorial 1  StarForge "User Manual"
.SH NAME
starforge\-tool\-tutorial \- Interactive CLI tutorials
.SH SYNOPSIS
\fBstarforge\-tool\-tutorial\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Interactive CLI tutorials
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
