.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract-explain 1  StarForge "User Manual"
.SH NAME
starforge\-contract\-explain \- Analyze and explain smart contract code using AI
.SH SYNOPSIS
\fBstarforge\-contract\-explain\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Analyze and explain smart contract code using AI
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
