.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-wallet-auth 1  StarForge "User Manual"
.SH NAME
starforge\-wallet\-auth \- SEP\-10 web authentication for Stellar anchors
.SH SYNOPSIS
\fBstarforge\-wallet\-auth\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
SEP\-10 web authentication for Stellar anchors
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
