.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract-security 1  StarForge "User Manual"
.SH NAME
starforge\-contract\-security \- Security hardening, validation, and monitoring
.SH SYNOPSIS
\fBstarforge\-contract\-security\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Security hardening, validation, and monitoring
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
