.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-deploy 1  StarForge "User Manual"
.SH NAME
starforge\-deploy \- Deploy a compiled Soroban contract and manage the lifecycle
.SH SYNOPSIS
\fBstarforge\-deploy\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Deploy a compiled Soroban contract and manage the lifecycle
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
