.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract-complete 1  StarForge "User Manual"
.SH NAME
starforge\-contract\-complete \- Smart contract completion assistant
.SH SYNOPSIS
\fBstarforge\-contract\-complete\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Smart contract completion assistant
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
