.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-deploy-schedule 1  StarForge "User Manual"
.SH NAME
starforge\-deploy\-schedule \- Schedule deployments for future execution
.SH SYNOPSIS
\fBstarforge\-deploy\-schedule\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Schedule deployments for future execution
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
