.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-ai-security-audit 1  StarForge "User Manual"
.SH NAME
starforge\-ai\-security\-audit \- AI\-powered security audit
.SH SYNOPSIS
\fBstarforge\-ai\-security\-audit\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
AI\-powered security audit
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
