.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-deploy-env 1  StarForge "User Manual"
.SH NAME
starforge\-deploy\-env \- Manage deployment environments (dev/staging/production)
.SH SYNOPSIS
\fBstarforge\-deploy\-env\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Manage deployment environments (dev/staging/production)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
