.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-tool-pr 1  StarForge "User Manual"
.SH NAME
starforge\-tool\-pr \- Check PR readiness (CI status and merge conflicts)
.SH SYNOPSIS
\fBstarforge\-tool\-pr\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Check PR readiness (CI status and merge conflicts)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
