.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-ai-deploy-test 1  StarForge "User Manual"
.SH NAME
starforge\-ai\-deploy\-test \- AI\-driven deployment testing
.SH SYNOPSIS
\fBstarforge\-ai\-deploy\-test\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
AI\-driven deployment testing
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
