.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH starforge-contract-health 1  StarForge "User Manual"
.SH NAME
starforge\-contract\-health \- Contract health monitoring and alerting
.SH SYNOPSIS
\fBstarforge\-contract\-health\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Contract health monitoring and alerting
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
