"""Runtime support for Python clients generated by StarForge."""

import asyncio
import json
import subprocess
from dataclasses import asdict, is_dataclass
from typing import Any, Optional


class ContractInvocationError(RuntimeError):
	"""Raised when the StarForge CLI cannot invoke a contract function."""


class ContractClient:
	"""Small, dependency-free runtime for generated contract clients."""

	def __init__(self, contract_id: str, network: str = "testnet", wallet: Optional[str] = None):
		self.contract_id = contract_id
		self.network = network
		self.wallet = wallet

	@staticmethod
	def encode_arg(value: Any) -> str:
		if isinstance(value, bool):
			return str(value).lower()
		if isinstance(value, bytes):
			return value.hex()
		if is_dataclass(value):
			value = asdict(value)
		if isinstance(value, (dict, list, tuple)):
			return json.dumps(value, separators=(",", ":"), default=str)
		return str(value)

	def invoke_args(self, function_name: str, **args: tuple[Any, str]) -> list[str]:
		command = ["starforge", "contract", "invoke", self.contract_id, function_name, "--network", self.network]
		for value, type_name in args.values():
			command.extend(["--arg", self.encode_arg(value), "--type", type_name])
		if self.wallet:
			command.extend(["--wallet", self.wallet, "--submit"])
		return command

	def invoke(self, function_name: str, *args: tuple[Any, str]) -> Any:
		command = ["starforge", "contract", "invoke", self.contract_id, function_name, "--network", self.network]
		for value, type_name in args:
			command.extend(["--arg", self.encode_arg(value), "--type", type_name])
		if self.wallet:
			command.extend(["--wallet", self.wallet, "--submit"])
		result = subprocess.run(command, capture_output=True, text=True)
		if result.returncode:
			detail = result.stderr.strip() or result.stdout.strip() or "unknown error"
			raise ContractInvocationError(f"{function_name} failed: {detail}")
		try:
			return json.loads(result.stdout)
		except json.JSONDecodeError:
			return result.stdout.strip()

	async def invoke_async(self, function_name: str, *args: tuple[Any, str]) -> Any:
		return await asyncio.to_thread(self.invoke, function_name, *args)
