//! Integration tests for the auto-generated command cheat sheet
//! (`docs/COMMAND_CHEATSHEET.md`), which is produced from clap metadata by
//! `build.rs`. These guards mirror the CI anti-drift job so local `cargo test`
//! catches a stale cheat sheet before it is committed.

use std::path::Path;

fn cheat_sheet() -> String {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/COMMAND_CHEATSHEET.md");
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read docs/COMMAND_CHEATSHEET.md: {}", e))
}

#[test]
fn cheat_sheet_exists_and_is_auto_generated() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/COMMAND_CHEATSHEET.md");
    assert!(
        path.exists(),
        "docs/COMMAND_CHEATSHEET.md must exist (generated by build.rs)"
    );
    let contents = cheat_sheet();
    assert!(
        contents.contains("Auto-generated") && contents.contains("build.rs"),
        "must declare it is auto-generated from clap metadata"
    );
    assert!(
        contents.contains("regenerate") || contents.contains("Regenerate"),
        "must describe how to regenerate the cheat sheet"
    );
}

#[test]
fn cheat_sheet_covers_top_level_commands() {
    let contents = cheat_sheet();
    for cmd in [
        "wallet",
        "contract",
        "deploy",
        "network",
        "template",
        "plugin",
        "ai",
        "config",
        "project",
        "tool",
        "completions",
    ] {
        assert!(
            contents.contains(&format!("| `{}` |", cmd)),
            "cheat sheet must cover the `{}` top-level command",
            cmd
        );
    }
}

#[test]
fn cheat_sheet_covers_major_subcommands() {
    let contents = cheat_sheet();
    for (group, sub) in [
        ("wallet", "create"),
        ("wallet", "auth"),
        ("contract", "generate-bindings"),
        ("contract", "storage"),
        ("deploy", "run --wasm"),
        ("network", "switch"),
        ("network", "node"),
        ("template", "init"),
        ("template", "registry"),
        ("ai", "local"),
        ("ai", "security-audit"),
        ("config", "set"),
        ("config", "flags"),
        ("project", "collab"),
        ("tool", "tutorial"),
    ] {
        assert!(
            contents.contains(&format!("## `{}` subcommands", group)),
            "cheat sheet must include a `{}` subcommand section",
            group
        );
        assert!(
            contents.contains(sub),
            "cheat sheet must cover the `{} {}` subcommand",
            group,
            sub
        );
    }
}

#[test]
fn cheat_sheet_excludes_internal_and_hidden_commands() {
    let contents = cheat_sheet();
    // `help` and `feature-flags` are no longer top-level commands, so they are
    // not in this list any more: `ai help` and `config flags` are ordinary verbs.
    for internal in ["`external`", "`autocomplete`", "`man`"] {
        assert!(
            !contents.contains(internal),
            "cheat sheet must exclude the internal command {}",
            internal
        );
    }
}

/// Issue #936: `--help` must not become a wall of 80+ top-level commands again.
#[test]
fn cheat_sheet_stays_within_the_top_level_budget() {
    let contents = cheat_sheet();
    let top_level = contents
        .lines()
        .skip_while(|line| !line.starts_with("## Top-level commands"))
        .skip(1)
        .take_while(|line| !line.starts_with("## "))
        .filter(|line| line.starts_with("| `"))
        .count();
    assert!(
        top_level <= 20,
        "expected at most 20 top-level commands in the cheat sheet, found {}",
        top_level
    );
    assert!(
        top_level >= 10,
        "expected the cheat sheet to still list the top-level commands, found {}",
        top_level
    );
}

#[test]
fn cheat_sheet_tables_are_malformed_free() {
    let contents = cheat_sheet();
    // Every table row must contain exactly two cells (Command | Description).
    // Escaped pipes (`\|`) are literal cell content, not delimiters, so replace
    // them with a non-pipe sentinel before splitting on the raw `|`.
    let mut rows = 0;
    let mut bad = 0;
    for line in contents.lines() {
        if line.starts_with('|') {
            rows += 1;
            let normalized = line.replace("\\|", "\u{0}");
            let cells = normalized.split('|').filter(|c| !c.is_empty()).count();
            // Header/separator rows are expected to have two cells as well.
            if cells != 2 {
                bad += 1;
            }
        }
    }
    assert!(
        rows >= 20,
        "expected a sizeable cheat sheet, found {} rows",
        rows
    );
    assert_eq!(bad, 0, "found {} malformed table rows", bad);
}
